### ISSUE TITLE
Search totally broken with The Silver Searcher in 1.3.0

### ISSUE THREAD

**Issue by lacostenycoder** [antelle/atom-codesearch#5]
Whatever was done in this release totally broke all searching.  Please revert this!!!
I had do disable the package completely.  It was working OK before.

**Comment by lacostenycoder** [comment]
Well now I'm not sure if this was a result of upgrade or now.  I forked and reverted locally to 1.2.0 and it still doesn't work at all.  Any ideas??

**Comment by lacostenycoder** [comment]
@joesolly OK thank you for sticking with me on this. So after adding symlink for cindex Google CodesSearch works now and very fast!  But no luck with ag aka The Silver Searcher.  But I guess I can live with this.  One more question for now:  Where is the index actually stored?
I have the default setting `Create per-project index files` ?  

Is there any point to allowing the other search types if we can't get them to work?

**Comment by joesolly** [comment]
@lacostenycoder Ok. You inspired me to do some digging myself, and I discovered that I too cannot get The Silver Searcher to work. I can Get The Platinum Searcher and RipGrep to work if I add `.` to the Search Path field.
![screen shot 2018-11-15 at 9 30 09 am](https://user-images.githubusercontent.com/5065964/48559187-1729a880-e8b9-11e8-838c-8b959ce02ae4.png)

The index appears to be stored in `~/.atom/packages/atom-codesearch/data` if you use the default create per-project index files. If you used the global one, I imagine it would use the default `~/.csearchindex`. I'm not sure what `cgrep` is used for, but `csearch` works on regular expressions, so I don't think you need it.

We could remove The Silver Searcher if you think it's worthwhile.

Since you just went through the process of installing Google CodeSearch (and I don't remember how to do it since I did it a long time ago), would you mind putting some steps into the README?

**Comment by lacostenycoder** [comment]
@joesolly Yeah, if we can't get `ag` search working, probably best to remove it, although not sure why it doesn't work.  But yeah let me see if I can retrace what I did to get the install setup correctly.  It was kinda of a hack-a-bitch! lol

**Comment by lacostenycoder** [comment]
I'll add these steps when have a chance, but basically these.
```
cd $HOME
brew install go

#add these to your shell i.e. ~/.bash_profile 
export PATH=$PATH:/usr/local/opt/go/libexec/bin
export GOPATH=$HOME/go

#install csearch
go get github.com/google/codesearch/cmd/...

#add require symlinks
ln -s ~/go/bin/csearch /usr/local/bin/csearch
ln -s ~/go/bin/cindex /usr/local/bin/cindex
```

**Comment by lacostenycoder** [comment]
fixed by https://github.com/antelle/atom-codesearch/pull/7
